name: PRFlow Bikes

on: 
  pull_request:
    branches:
    - master
    paths:
    - samples/BikeSharingApp/Bikes/*    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - uses: s-tuli/githubactioncomment/actions/AddComment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_HOST_SUFFIX: ${{ secrets.HOST_SUFFIX }}
        GITHUB_PARENT_SPACE: ${{ secrets.PARENT_SPACE }}
      with:        
        pull_number: '3'
        body: 'Hi, this is my test!'        
        path: 'samples/BikeSharingApp/Bikes/server.js'
        position: '1'    
    - uses: azure/container-actions/docker-login@master
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build samples/BikeSharingApp/Bikes/ -t ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
      
    - uses: azure/k8s-actions/aks-set-context@master
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: BikeSharingAKS
        resource-group: bikesharing
                
    - name: Create child namespaces and add Dev Spaces labels
      run:  |
        if [ -n "$(kubectl get namespace $GITHUB_HEAD_REF --ignore-not-found -o name)" ]; then exit 0; fi
        kubectl create namespace $GITHUB_HEAD_REF
        kubectl label namespace $GITHUB_HEAD_REF azds.io/parent-space=${{ secrets.PARENT_SPACE }} 
        kubectl label namespace $GITHUB_HEAD_REF azds.io/space=true
        
    - uses: azure/k8s-actions/k8s-create-secret@master
      with:
        namespace: ${{ github.head_ref }}
        container-registry-url: ${{ secrets.CONTAINER_REGISTRY }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ secrets.IMAGE_PULL_SECRET }}
        
    - name: Helm Instal PR
      run: |
        helm upgrade --install --namespace $GITHUB_HEAD_REF bikesharing-$GITHUB_HEAD_REF samples/BikeSharingApp/Bikes/charts/bikes --set "image.repository=${{ secrets.CONTAINER_REGISTRY }}/bikes,image.tag=$GITHUB_SHA,imagePullSecrets[0].name=${{ secrets.IMAGE_PULL_SECRET }},ingress.hosts[0]=$GITHUB_HEAD_REF.s.${{ secrets.PARENT_SPACE }}.bikesharing.${{ secrets.HOST_SUFFIX }},ingress.annotations.\"kubernetes\\.io/ingress\\.class\"=traefik-azds"
        echo This succeeded: http://$GITHUB_HEAD_REF.s.${{ secrets.PARENT_SPACE }}.bikesharingweb.${{ secrets.HOST_SUFFIX }}/
