name: PRFlow Bikes

on: 
  pull_request:
    branches:
    - master
    paths:
    - samples/BikeSharingApp/Bikes/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@master    

    - uses: azure/docker-login@releases/v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build samples/BikeSharingApp/Bikes/ -t ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/bikes:$GITHUB_SHA
      
    - uses: azure/k8s-actions/aks-set-context@master
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Create valid child namespace name
      id: generate-child-space-name
      run: |
        branch=${GITHUB_HEAD_REF::63}        
        branch=$(echo ${branch//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
        echo ::set-output name=result::$branch         
    
    - name: Create child namespaces and add Dev Spaces labels
      run:  |
        if [ -n "$(kubectl get namespace ${{steps.generate-child-space-name.outputs.result}} --ignore-not-found -o name)" ]; then exit 0; fi
        kubectl create namespace ${{steps.generate-child-space-name.outputs.result}}
        kubectl label namespace ${{steps.generate-child-space-name.outputs.result}} azds.io/parent-space=${{ secrets.MASTER_SPACE }} 
        kubectl label namespace ${{steps.generate-child-space-name.outputs.result}} azds.io/space=true
        kubectl label namespace ${{steps.generate-child-space-name.outputs.result}} azds.io/pull-request-space=true
        
    - uses: azure/k8s-actions/k8s-create-secret@master
      with:
        namespace: ${{ steps.generate-child-space-name.outputs.result }}
        container-registry-url: ${{ secrets.CONTAINER_REGISTRY }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ secrets.IMAGE_PULL_SECRET }}

    - name: Create valid release-name
      id: generate-release-name
      run: |
        release=bikesharing-$GITHUB_HEAD_REF
        release=${release::53}
        release=$(echo ${release//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
        echo ::set-output name=result::$release

    - name: Install Helm for client
      id: install-helm-client
      run: |
        set -e        
        clientversion=$(helm version --client --short | cut -d' ' -f2 | cut -d'+' -f1)
        serverversion=$(helm version --server --short | cut -d' ' -f2 | cut -d'+' -f1)
        if [ ! -n "$serverversion" ]; then
          echo "Please install Helm on the server!" 1>&2
          exit 1
        elif [ "$clientversion" == "$serverversion" ]; then   
          echo The client and server Helm Versions are equal
          echo ::set-output name=result::
        else
          tmp_dir=$(mktemp -d)      
          export DESIRED_VERSION=$serverversion HELM_INSTALL_DIR=$tmp_dir          
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
          chmod 700 get_helm.sh
          ./get_helm.sh
          echo ::set-output name=result::$tmp_dir/
        fi

    - name: Helm Upgrade PR
      run: |        
        ${{steps.install-helm-client.outputs.result}}helm upgrade \
          --install  ${{steps.generate-release-name.outputs.result}} samples/BikeSharingApp/Bikes/charts/bikes \
          --namespace ${{steps.generate-child-space-name.outputs.result}} \
          --set image.repository=${{ secrets.CONTAINER_REGISTRY }}/bikes \
          --set image.tag=$GITHUB_SHA \
          --set imagePullSecrets[0].name=${{ secrets.IMAGE_PULL_SECRET }}
 
    - uses: azure/dev-spaces/actions/add-review-url@s-tuli/ConvertGitHubActionToTypeScript              
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}  
        host: ${{ secrets.HOST }}
        child-space: ${{steps.generate-child-space-name.outputs.result}}
        protocol: 'http'